import { describe, expect, test } from "bun:test";
import type { ChildBinding, Proposal, RoutingSnapshot } from "../../src/contracts";
import { config, analysis } from "../support/fixtures";
import { decide, type AvailableModel } from "../../src/core/router";
import { ChildController, type ConfigurationSnapshot, type ConfigurationResult, type ConfigureRequest, type ControllerOptions } from "../../src/children/controller";

const model = (id:string, input=1):AvailableModel => ({provider:"local",id,cost:{input,output:1,cacheRead:0,cacheWrite:0}});
const beforeModel=model("before"), afterModel=model("after"), cheapModel=model("cheap");
function deferred() { let release!:()=>void; const promise=new Promise<void>(yes=>release=yes);return {promise,release}; }
function fixture() {
 const runtime:RoutingSnapshot={owner:"owner",generation:1,config:config()};
 Object.assign(runtime.config,{stickiness:false,kindModels:{},kindMinimumTier:{},confidenceThreshold:0});
 runtime.config.cache.aware=false;runtime.config.routes={quick:[{provider:"local",model:"cheap"}],standard:[{provider:"local",model:"before"}],high:[{provider:"local",model:"after",thinkingLevel:"high"}],premium:[],xpremium:[]};
 const session={sessionId:"sdk-child",isIdle:true,isCompacting:false,model:beforeModel,thinkingLevel:"off",subscribe:()=>()=>{},getContextUsage:()=>({tokens:100000,contextWindow:200000,percent:50})};
 const binding:ChildBinding={owner:"owner",id:"child",toolCallId:"spawn",session:session as unknown as ChildBinding["session"],sessionKey:"sdk-child",generation:1,disposed:false};
 const record={id:"child",type:"worker",status:"completed",startedAt:1,toolUses:0,compactionCount:0,lifetimeUsage:{input:0,output:0,cacheWrite:0},session,toolCallId:"spawn"};
 let snapshot:ConfigurationSnapshot={sessionId:"sdk-child",revision:0,model:beforeModel,thinkingLevel:"off"};
 const receipts=new Map<string,ConfigurationResult>(), requests:ConfigureRequest[]=[];
 let mutate:(r:ConfigureRequest)=>Promise<ConfigurationResult>=async r=>{
  if(r.signal?.aborted)return {status:"rejected",operationId:r.operationId,reason:"cancelled"};
  const before=structuredClone(snapshot);
  const same=before.model?.id===r.model.id && before.model.provider===r.model.provider && before.thinkingLevel===r.thinking;
  snapshot={sessionId:before.sessionId,revision:before.revision+(same?0:1),model:{...r.model},thinkingLevel:r.thinking};
  session.model={...r.model};session.thinkingLevel=r.thinking;
  const result:ConfigurationResult={status:same?"noop":"committed",operationId:r.operationId,before,after:structuredClone(snapshot),revision:snapshot.revision,notificationErrors:[]};
  if(!same)receipts.set(r.operationId,result);return result;
 };
 const registry={getRecord:(id:string)=>id===record.id?record:undefined,getIdleChildConfigurationSnapshot:(id:string)=>({status:"ready",childId:id,snapshot:structuredClone(snapshot)}),configureIdleChild:async(r:ConfigureRequest)=>{requests.push(r);return mutate(r);},getIdleChildConfigurationReceipt:(r:{operationId:string})=>receipts.get(r.operationId)??{status:"rejected",operationId:r.operationId,reason:"not-found"}};
 const options:ControllerOptions={getRuntime:()=>runtime,getBinding:()=>binding,getRegistry:()=>registry,getCandidates:()=>({status:"ready",models:[beforeModel,afterModel,cheapModel]}),getSpend:()=>({today:0,month:0,pressure:0})};
 const controller=new ChildController(options);
 const proposal=():Proposal=>{const a=analysis({complexity:2,budgetIntensity:2,deepReasoning:0.5});return {analysis:a,decision:decide(a,runtime.config,{models:[beforeModel,afterModel,cheapModel],spend:{today:0,month:0,pressure:0}})};};
 return {runtime,binding,record,session,registry,options,controller,proposal,requests,receipts,get snapshot(){return snapshot;},set snapshot(s:ConfigurationSnapshot){snapshot=s;},setMutate:(m:typeof mutate)=>{mutate=m;}};
}

describe("retained child atomic controller",()=>{
 test("apply pins the exact pair; revert restores both fields and consumes the stack",async()=>{const f=fixture();const r=await f.controller.apply(f.binding,f.proposal(),f.runtime);expect(r.status).toBe("committed");expect(f.snapshot).toMatchObject({model:{id:"after"},thinkingLevel:"high"});expect(f.controller.history(f.binding)).toHaveLength(1);expect((await f.controller.revert(f.binding,f.runtime)).status).toBe("committed");expect(f.snapshot).toMatchObject({model:{id:"before"},thinkingLevel:"off"});expect(f.controller.history(f.binding)).toHaveLength(0);expect((await f.controller.revert(f.binding,f.runtime)).reason).toBe("history-empty");});
 test("unpinned target preserves previous level exactly and off is a real pin",async()=>{const f=fixture();f.snapshot={...f.snapshot,thinkingLevel:"max"};f.session.thinkingLevel="max";delete f.runtime.config.routes.high[0].thinkingLevel;expect((await f.controller.apply(f.binding,f.proposal(),f.runtime)).status).toBe("committed");expect(f.snapshot.thinkingLevel).toBe("max");f.runtime.config.routes.quick[0].thinkingLevel="off";const a=analysis({complexity:0,budgetIntensity:0,deepReasoning:0.1});const p={analysis:a,decision:decide(a,f.runtime.config,{models:[cheapModel],spend:{today:0,month:0,pressure:0}})};expect((await f.controller.apply(f.binding,p,f.runtime)).status).toBe("committed");expect(f.snapshot.thinkingLevel).toBe("off");});
 for(const kind of ["parent","owner","generation","disposed","foreign","session","correlation","running","queued","compaction"] as const)test(`refuses ${kind} binding without mutation`,async()=>{const f=fixture();if(kind==="parent")f.binding.id="parent";if(kind==="owner")f.binding.owner="other";if(kind==="generation")f.binding.generation=0;if(kind==="disposed")f.binding.disposed=true;if(kind==="foreign")Object.assign(f.record,{parentAgentId:"foreign"});if(kind==="session")f.record.session={...f.session};if(kind==="correlation")f.record.toolCallId="other";if(kind==="running"||kind==="queued")f.record.status=kind;if(kind==="compaction")f.session.isCompacting=true;const r=await f.controller.apply(f.binding,f.proposal(),f.runtime);expect(r.status).toBe("rejected");expect(f.requests).toHaveLength(0);});
 test("published registry missing 3B is explicitly unsupported",async()=>{const f=fixture();f.options.getRegistry=()=>({getRecord:f.registry.getRecord});expect((await f.controller.apply(f.binding,f.proposal(),f.runtime)).reason).toBe("unsupported");expect(f.requests).toHaveLength(0);});
 test("missing proposal or previous model is never filled from parent defaults",async()=>{for(const previous of [false,true]){const f=fixture();if(previous)f.snapshot={...f.snapshot,model:undefined};const p=f.proposal();if(!previous)p.decision!.model=undefined;expect((await f.controller.apply(f.binding,p,f.runtime)).status).toBe("rejected");expect(f.requests).toHaveLength(0);}});
 test("missing analysis refuses policy recomputation",async()=>{const f=fixture();const p=f.proposal();delete p.analysis;expect((await f.controller.apply(f.binding,p,f.runtime)).reason).toBe("analysis-required");});
 for(const mode of ["notify","keep","cancel","cheaper","selected"] as const)test(`mode ${mode} has explicit noninteractive semantics`,async()=>{const f=fixture();f.runtime.config.mode=mode==="notify"?"notify":"confirm";f.runtime.config.routes.standard[0].thinkingLevel="low";f.options.ui={select:async(_title,items)=>mode==="selected"?items[0]:mode==="cheaper"?items[1]:undefined};if(mode==="cancel")f.options.ui={select:async()=>{f.controller.invalidate();return "Selected: local/after";}};const r=await f.controller.apply(f.binding,f.proposal(),f.runtime);if(mode==="selected"||mode==="cheaper"){expect(r.status).toBe("committed");expect(f.snapshot.model?.id).toBe(mode==="selected"?"after":"before");}else{expect(f.requests).toHaveLength(0);expect(f.controller.history(f.binding)).toHaveLength(0);}});
 test("confirm without UI uses documented auto; noop never creates history",async()=>{const f=fixture();f.runtime.config.mode="confirm";f.runtime.config.routes.high=[{provider:"local",model:"before",thinkingLevel:"off"}];expect((await f.controller.apply(f.binding,f.proposal(),f.runtime)).status).toBe("noop");expect(f.controller.history(f.binding)).toHaveLength(0);});
 for(const policy of ["same-tier","deadband","big-jump","unknown-price","stickiness"] as const)test(`existing decide cache policy: ${policy}`,async()=>{const f=fixture();f.runtime.config.cache={aware:true,deadband:0.2,maxPenaltyUsd:0.01,bypassTierDelta:2};f.runtime.config.routes.standard=[{provider:"local",model:"after"}];f.runtime.config.routes.high=[{provider:"local",model:"after"}];let current=beforeModel;let a=analysis({complexity:1,budgetIntensity:1,deepReasoning:0.5});if(policy==="deadband")a=analysis({complexity:1.55,budgetIntensity:1.55,deepReasoning:0.5});if(policy==="big-jump")a=analysis({complexity:3,budgetIntensity:3,deepReasoning:0.5});if(policy==="big-jump")f.runtime.config.routes.premium=[{provider:"local",model:"after"}];if(policy==="unknown-price")current={provider:"local",id:"before"};if(policy==="stickiness"){f.runtime.config.stickiness=true;f.runtime.config.routes.standard=[{provider:"local",model:"before",thinkingLevel:"high"}];}
  f.options.getCandidates=()=>({status:"ready",models:[current,policy==="unknown-price"?{provider:"local",id:"after"}:model("after",20),cheapModel]});
  // Reverse tier lookup of the actual child must still find standard.
  f.runtime.config.routes.standard.push({provider:"local",model:"before"});
  const p={analysis:a,decision:decide(a,f.runtime.config,{models:[beforeModel,afterModel],spend:{today:0,month:0,pressure:0}})};
  const r=await f.controller.apply(f.binding,p,f.runtime);if(["same-tier","deadband","stickiness"].includes(policy)){expect(r.status).toBe("held");expect(f.requests).toHaveLength(0);}else expect(r.status).toBe("committed");
 });
 test("candidate refusal reason must be a static string, not a coercible object",async()=>{const f=fixture();f.options.getCandidates=()=>({status:"rejected",reason:{private:"key",toString:()=>"scope-denied"}} as unknown as ReturnType<ControllerOptions["getCandidates"]>);const r=await f.controller.apply(f.binding,f.proposal(),f.runtime);expect(r.reason).toBe("invalid-candidates");expect(JSON.stringify(r)).not.toContain("private");expect(f.requests).toHaveLength(0);});
 test("candidate scope rejection has no unfiltered fallback",async()=>{const f=fixture();f.options.getCandidates=()=>({status:"rejected",reason:"scope-denied"});expect((await f.controller.apply(f.binding,f.proposal(),f.runtime)).reason).toBe("scope-denied");expect(f.requests).toHaveLength(0);});
 test("per child guard refuses rather than queuing concurrent control",async()=>{const f=fixture(),gate=deferred();f.options.getSpend=async()=>{await gate.promise;return {today:0,month:0,pressure:0};};const first=f.controller.apply(f.binding,f.proposal(),f.runtime);expect((await f.controller.apply(f.binding,f.proposal(),f.runtime)).reason).toBe("in-flight");gate.release();expect((await first).status).toBe("committed");expect(f.requests).toHaveLength(1);});
 for(const change of ["owner","config","binding","off","disposed"] as const)test(`cancellation/revalidation after awaited spend: ${change}`,async()=>{const f=fixture(),gate=deferred();f.options.getSpend=async()=>{await gate.promise;return {today:0,month:0,pressure:0};};const p=f.controller.apply(f.binding,f.proposal(),f.runtime);if(change==="owner")f.runtime.owner="other";if(change==="config")f.runtime.generation++;if(change==="binding")f.binding.generation++;if(change==="off")f.runtime.config.enabled=false;if(change==="disposed")f.controller.dispose();gate.release();expect((await p).status).toBe("rejected");expect(f.requests).toHaveLength(0);});
 test("reentrant runtime/candidate/ID callbacks cannot admit after disposal",async()=>{for(const cb of ["runtime","candidates","id"]){const f=fixture();if(cb==="runtime")f.options.getRuntime=()=>{f.controller.dispose();return f.runtime;};if(cb==="candidates")f.options.getCandidates=()=>{f.controller.dispose();return {status:"ready",models:[beforeModel,afterModel]};};if(cb==="id")f.options.operationId=()=>{f.controller.dispose();return crypto.randomUUID();};expect((await f.controller.apply(f.binding,f.proposal(),f.runtime)).status).toBe("rejected");expect(f.requests).toHaveLength(0);}});
 for(const reason of ["busy","stale","unauthorized","cancelled","unsupported","scope-unknown","scope-denied"] as const)test(`definitive native ${reason} does not alter history`,async()=>{const f=fixture();f.setMutate(async r=>({status:"rejected",operationId:r.operationId,reason}));expect((await f.controller.apply(f.binding,f.proposal(),f.runtime)).reason).toBe(reason);expect(f.controller.history(f.binding)).toHaveLength(0);});
 test("lost acknowledgement lookup recovers once with original operation ID",async()=>{const f=fixture();const native=f.registry.configureIdleChild;f.registry.configureIdleChild=async r=>{await native(r);throw Error("secret transport");};const r=await f.controller.apply(f.binding,f.proposal(),f.runtime);expect(r.status).toBe("committed");expect(f.requests).toHaveLength(1);expect(f.controller.history(f.binding)).toHaveLength(1);});
 test("lookup precedes one identical request/signal retry after a lost call",async()=>{const f=fixture();const native=f.registry.configureIdleChild;let first=true,lookups=0;const lookup=f.registry.getIdleChildConfigurationReceipt;f.registry.getIdleChildConfigurationReceipt=r=>{lookups++;return lookup(r);};let original:ConfigureRequest|undefined;f.registry.configureIdleChild=async r=>{if(first){first=false;original=r;throw Error("no acknowledgement");}expect(lookups).toBe(1);expect(r).toBe(original!);return native(r);};expect((await f.controller.apply(f.binding,f.proposal(),f.runtime)).status).toBe("committed");});
 test("a new binding generation cannot bypass degradation of the same SDK lifetime",async()=>{const f=fixture();f.setMutate(async()=>{throw Error("unresolved auth");});expect((await f.controller.apply(f.binding,f.proposal(),f.runtime)).status).toBe("degraded");const n=f.requests.length;f.binding.generation++;expect((await f.controller.apply(f.binding,f.proposal(),f.runtime)).status).toBe("degraded");expect(f.requests).toHaveLength(n);expect(f.controller.metadata(f.binding).status).toBe("degraded");});
 test("synthetic public 3B unresolved outcome survives controller replacement, not history",async()=>{const f=fixture();f.setMutate(async()=>{throw Error("unresolved");});expect((await f.controller.apply(f.binding,f.proposal(),f.runtime)).status).toBe("degraded");f.controller.dispose();f.binding.generation++;const c=new ChildController(f.options),n=f.requests.length;expect(c.metadata(f.binding)).toMatchObject({status:"degraded",depth:0});expect((await c.apply(f.binding,f.proposal(),f.runtime)).status).toBe("degraded");expect(f.requests).toHaveLength(n);});
 for(const outcome of ["unresolved","committed","noop","rejected"] as const)test(`synthetic public 3B pending lease survives replacement and resolves truthfully: ${outcome}`,async()=>{
  const f=fixture(),gate=deferred(),entered=deferred();const native=f.registry.configureIdleChild;
  if(outcome==="noop")f.runtime.config.routes.high=[{provider:"local",model:"before",thinkingLevel:"off"}];
  f.registry.configureIdleChild=async r=>{entered.release();await gate.promise;if(outcome==="unresolved")throw Error("late unresolved");if(outcome==="rejected")return {status:"rejected",operationId:r.operationId,reason:"cancelled"};return native({...r,signal:undefined});};
  const pending=f.controller.apply(f.binding,f.proposal(),f.runtime);await entered.promise;f.controller.dispose();f.binding.generation++;
  const c=new ChildController(f.options),replacement=c.apply(f.binding,f.proposal(),f.runtime);gate.release();expect((await replacement).reason).toBe("in-flight");
  expect((await pending).status).toBe(outcome==="unresolved"?"degraded":outcome==="rejected"?"rejected":outcome);
  expect(c.history(f.binding)).toHaveLength(0);
  if(outcome==="unresolved"){expect(c.metadata(f.binding).status).toBe("degraded");expect((await c.apply(f.binding,f.proposal(),f.runtime)).status).toBe("degraded");}
  else {f.registry.configureIdleChild=native;expect((await c.apply(f.binding,f.proposal(),f.runtime)).status).toBe(outcome==="rejected"?"committed":"noop");}
 });
 test("unknown outcome degrades and blocks all later mutations",async()=>{const f=fixture();f.setMutate(async()=>{throw Error("private key");});expect((await f.controller.apply(f.binding,f.proposal(),f.runtime)).status).toBe("degraded");const n=f.requests.length;expect((await f.controller.apply(f.binding,f.proposal(),f.runtime)).status).toBe("degraded");expect(f.requests).toHaveLength(n);});
 test("malformed snapshots refuse; malformed acknowledgement degrades",async()=>{const f=fixture();f.snapshot={...f.snapshot,revision:-1};expect((await f.controller.apply(f.binding,f.proposal(),f.runtime)).reason).toBe("invalid-snapshot");const g=fixture();g.setMutate(async r=>({status:"committed",operationId:r.operationId,before:g.snapshot,after:{...g.snapshot,revision:1,model:afterModel,thinkingLevel:"off"},revision:1,notificationErrors:[]}));expect((await g.controller.apply(g.binding,g.proposal(),g.runtime)).status).toBe("degraded");expect(g.controller.history(g.binding)).toHaveLength(0);});
 test("notification diagnostics are committed, never compensation",async()=>{const f=fixture();const native=f.registry.configureIdleChild;f.registry.configureIdleChild=async r=>{const result=await native(r);return result.status==="rejected"?result:{...result,notificationErrors:["private diagnostic"]};};const result=await f.controller.apply(f.binding,f.proposal(),f.runtime);expect(result.status).toBe("committed");expect(result.reason).toBe("committed-with-diagnostics");expect(f.controller.history(f.binding)).toHaveLength(1);expect(f.requests).toHaveLength(1);});
 test("multilevel revert follows own monotonic cursor, not obsolete historic revisions",async()=>{const f=fixture();await f.controller.apply(f.binding,f.proposal(),f.runtime);const a=analysis({complexity:0,budgetIntensity:0,deepReasoning:0.1}),p={analysis:a,decision:decide(a,f.runtime.config,{models:[cheapModel],spend:{today:0,month:0,pressure:0}})};await f.controller.apply(f.binding,p,f.runtime);expect(f.controller.history(f.binding)).toHaveLength(2);expect((await f.controller.revert(f.binding,f.runtime)).status).toBe("committed");expect((await f.controller.revert(f.binding,f.runtime)).status).toBe("committed");expect(f.snapshot.revision).toBe(4);expect(f.snapshot.model?.id).toBe("before");});
 test("external ABA revision refuses revert without changing target/history",async()=>{const f=fixture();await f.controller.apply(f.binding,f.proposal(),f.runtime);f.snapshot={...f.snapshot,revision:8};const n=f.requests.length;expect((await f.controller.revert(f.binding,f.runtime)).reason).toBe("history-conflict");expect(f.requests).toHaveLength(n);expect(f.controller.history(f.binding)).toHaveLength(1);});
 test("revert confirm offers only exact restore or keep, never cheaper/cache alternative",async()=>{const f=fixture();await f.controller.apply(f.binding,f.proposal(),f.runtime);f.runtime.config.mode="confirm";f.runtime.config.cache.aware=true;let labels:string[]=[];f.options.ui={select:async(_t,items)=>{labels=items;return items[0];}};expect((await f.controller.revert(f.binding,f.runtime)).status).toBe("committed");expect(labels).toHaveLength(2);expect(labels.join()).not.toContain("Cheaper");expect(f.snapshot).toMatchObject({model:{id:"before"},thinkingLevel:"off"});});
 test("operation UUIDs are monotonic despite a backwards clock",async()=>{const f=fixture();let now=7;f.options.now=()=>now;await f.controller.apply(f.binding,f.proposal(),f.runtime);now=0;await f.controller.revert(f.binding,f.runtime);expect(f.requests[0].operationId.startsWith("00000000-0007-7")).toBe(true);expect(f.requests[1].operationId.startsWith("00000000-0008-7")).toBe(true);expect(f.requests[1].operationId>f.requests[0].operationId).toBe(true);});
 test("reentrant clock disposal refuses before native admission",async()=>{const f=fixture();f.options.now=()=>{f.controller.dispose();return 7;};expect((await f.controller.apply(f.binding,f.proposal(),f.runtime)).status).toBe("rejected");expect(f.requests).toHaveLength(0);});
 test("malformed mismatching proposal pair is not silently accepted",async()=>{const f=fixture();const p=f.proposal();p.decision!.target.model="foreign";expect((await f.controller.apply(f.binding,p,f.runtime)).reason).toBe("invalid-proposal");expect(f.requests).toHaveLength(0);});
 test("candidate callbacks cannot rewrite the captured admission generation",async()=>{const f=fixture();f.options.getCandidates=(b,r)=>{f.binding.generation=2;b.generation=2;f.runtime.generation=2;r.generation=2;return {status:"ready",models:[beforeModel,afterModel]};};expect((await f.controller.apply(f.binding,f.proposal(),f.runtime)).status).toBe("rejected");expect(f.requests).toHaveLength(0);});
 test("returned receipt mutation cannot rewrite the exact revert target",async()=>{const f=fixture();const r=await f.controller.apply(f.binding,f.proposal(),f.runtime);(r.receipt!.before.model as {provider:string;id:string}).id="after";expect((await f.controller.revert(f.binding,f.runtime)).status).toBe("committed");expect(f.snapshot.model?.id).toBe("before");});
 test("host cancellation reaches a pending native request without changing history",async()=>{const f=fixture(),signal=new AbortController(),gate=deferred();f.options.signal=signal.signal;const entered=deferred();let nativeSignal:AbortSignal|undefined;f.setMutate(async r=>{nativeSignal=r.signal;entered.release();await gate.promise;return {status:"rejected",operationId:r.operationId,reason:r.signal?.aborted?"cancelled":"invalid"};});const pending=f.controller.apply(f.binding,f.proposal(),f.runtime);await entered.promise;signal.abort();gate.release();expect((await pending).status).toBe("rejected");expect(nativeSignal?.aborted).toBe(true);expect(f.controller.history(f.binding)).toHaveLength(0);});
 for(const defect of ["operation","session","before-model","before-thinking","after-model","after-thinking","revision","reason","diagnostics"] as const)test(`malformed receipt ${defect} degrades without false history`,async()=>{const f=fixture();f.setMutate(async r=>{const value:Record<string,unknown>={status:"committed",operationId:r.operationId,before:f.snapshot,after:{...f.snapshot,revision:1,model:afterModel,thinkingLevel:"high"},revision:1,notificationErrors:[]};if(defect==="operation")value.operationId="wrong";if(defect==="session")value.after={...(value.after as ConfigurationSnapshot),sessionId:"foreign"};if(defect==="before-model")value.before={...f.snapshot,model:afterModel};if(defect==="before-thinking")value.before={...f.snapshot,thinkingLevel:"high"};if(defect==="after-model")value.after={...(value.after as ConfigurationSnapshot),model:beforeModel};if(defect==="after-thinking")value.after={...(value.after as ConfigurationSnapshot),thinkingLevel:"off"};if(defect==="revision")value.revision=0;if(defect==="reason")Object.assign(value,{status:"rejected",reason:"PRIVATE invalid reason"});if(defect==="diagnostics")value.notificationErrors=[undefined];return value as unknown as ConfigurationResult;});const result=await f.controller.apply(f.binding,f.proposal(),f.runtime);expect(result.status).toBe("degraded");expect(JSON.stringify(result)).not.toContain("PRIVATE");expect(f.controller.history(f.binding)).toHaveLength(0);});
 for(const defect of ["child","session","revision","level","model","reason"] as const)test(`malformed snapshot ${defect} refuses before native call`,async()=>{const f=fixture();const value:Record<string,unknown>={status:"ready",childId:f.binding.id,snapshot:f.snapshot};if(defect==="child")value.childId="parent";if(defect==="session")value.snapshot={...f.snapshot,sessionId:"parent-session"};if(defect==="revision")value.snapshot={...f.snapshot,revision:NaN};if(defect==="level")value.snapshot={...f.snapshot,thinkingLevel:"INVALID"};if(defect==="model")value.snapshot={...f.snapshot,model:{provider:"local"}};if(defect==="reason")Object.assign(value,{status:"rejected",reason:{private:"key"}});const registry={...f.registry,getIdleChildConfigurationSnapshot:()=>value};f.options.getRegistry=()=>registry;expect((await f.controller.apply(f.binding,f.proposal(),f.runtime)).reason).toBe("invalid-snapshot");expect(f.requests).toHaveLength(0);});
 test("receipt lookup denial after lost ack is unresolved, never an invented rollback",async()=>{const f=fixture();const native=f.registry.configureIdleChild;f.registry.configureIdleChild=async r=>{await native(r);throw Error("lost ack");};f.options.getRegistry=()=>({...f.registry,getIdleChildConfigurationReceipt:(r:{operationId:string})=>({status:"rejected",operationId:r.operationId,reason:"unauthorized"})});const registry=f.options.getRegistry();f.options.getRegistry=()=>registry;expect((await f.controller.apply(f.binding,f.proposal(),f.runtime)).status).toBe("degraded");expect(f.snapshot.model?.id).toBe("after");expect(f.requests).toHaveLength(1);expect(f.controller.history(f.binding)).toHaveLength(0);});
 test("runtime changes during confirmation and reentrant reads refuse",async()=>{for(const cb of ["ui","binding","registry"] as const){const f=fixture();if(cb==="ui"){f.runtime.config.mode="confirm";f.options.ui={select:async(_t,items)=>{f.runtime.generation++;return items[0];}};}if(cb==="binding")f.options.getBinding=()=>{f.controller.invalidate();return f.binding;};if(cb==="registry")f.options.getRegistry=()=>{f.controller.invalidate();return f.registry;};expect((await f.controller.apply(f.binding,f.proposal(),f.runtime)).status).toBe("rejected");expect(f.requests).toHaveLength(0);}});
 test("warnings throwing cannot turn a native refusal or degraded state into success",async()=>{const f=fixture();f.options.warn=()=>{throw Error("private warning");};f.setMutate(async()=>{throw Error("private auth");});expect((await f.controller.apply(f.binding,f.proposal(),f.runtime)).status).toBe("degraded");expect(f.controller.metadata(f.binding).status).toBe("degraded");});
 test("new SDK or owner lifetime cannot inherit a prior receipt stack",async()=>{const f=fixture();await f.controller.apply(f.binding,f.proposal(),f.runtime);const replacement={...f.binding,session:{...f.session} as unknown as ChildBinding["session"]};expect(f.controller.history(replacement)).toHaveLength(0);expect(f.controller.history({...f.binding,owner:"other"})).toHaveLength(0);expect(f.controller.history({...f.binding,generation:2})).toHaveLength(0);expect((await f.controller.revert(replacement,f.runtime)).status).toBe("rejected");});
 test("host invalidation acquisition and disposal release cleanup exactly once",async()=>{const f=fixture();let notify:()=>void=()=>{},releases=0;const c=new ChildController({...f.options,onInvalidate:fn=>{notify=fn;return ()=>{releases++;throw Error("private cleanup");};}});notify();expect((await c.apply(f.binding,f.proposal(),f.runtime)).status).toBe("rejected");c.dispose();c.dispose();expect(releases).toBe(1);let immediateRelease=0;const d=new ChildController({...f.options,onInvalidate:fn=>{fn();return ()=>{immediateRelease++;};}});expect(immediateRelease).toBe(1);expect((await d.apply(f.binding,f.proposal(),f.runtime)).status).toBe("rejected");});
 test("revert notify/keep/rejection preserve historical exact pair",async()=>{for(const mode of ["notify","keep","denied"] as const){const f=fixture();await f.controller.apply(f.binding,f.proposal(),f.runtime);const original=f.controller.history(f.binding);if(mode==="notify")f.runtime.config.mode="notify";if(mode==="keep"){f.runtime.config.mode="confirm";f.options.ui={select:async()=>undefined};}if(mode==="denied")f.setMutate(async r=>({status:"rejected",operationId:r.operationId,reason:"unauthorized"}));const r=await f.controller.revert(f.binding,f.runtime);expect(r.status).not.toBe("committed");expect(f.controller.history(f.binding)).toEqual(original);expect(f.snapshot.model?.id).toBe("after");}});
 for(const defect of ["generation","mode"] as const)test(`malformed runtime ${defect} refuses admission`,async()=>{const f=fixture();if(defect==="generation")f.runtime.generation=-1;else f.runtime.config.mode="INVALID" as RoutingSnapshot["config"]["mode"];expect((await f.controller.apply(f.binding,f.proposal(),f.runtime)).status).toBe("rejected");expect(f.requests).toHaveLength(0);});
 test("read-only metadata cannot leak a different SDK lifetime stack",async()=>{const f=fixture();await f.controller.apply(f.binding,f.proposal(),f.runtime);const binding={...f.binding,session:{...f.session} as unknown as ChildBinding["session"]};expect(f.controller.metadata(binding).depth).toBe(0);});
 test("post-commit throwing validation cannot erase acknowledged truth",async()=>{const f=fixture();const native=f.registry.configureIdleChild;f.registry.configureIdleChild=async r=>{const result=await native(r);f.options.getRuntime=()=>{throw Error("private runtime");};return result;};expect((await f.controller.apply(f.binding,f.proposal(),f.runtime)).status).toBe("committed");expect(f.controller.history(f.binding)).toHaveLength(1);expect(f.controller.metadata(f.binding).status).toBe("invalidated");});
 test("invalidation before any binding blocks future control",async()=>{const f=fixture();f.controller.invalidate();expect((await f.controller.apply(f.binding,f.proposal(),f.runtime)).status).toBe("rejected");expect(f.requests).toHaveLength(0);});
 test("proposal captured before external awaits cannot be mutated into a new policy",async()=>{const f=fixture(),gate=deferred();f.options.getSpend=async()=>{await gate.promise;return {today:0,month:0,pressure:0};};const p=f.proposal(),pending=f.controller.apply(f.binding,p,f.runtime);p.analysis!.complexity=0;p.analysis!.budgetIntensity=0;gate.release();expect((await pending).status).toBe("committed");expect(f.snapshot.model?.id).toBe("after");});
 test("abort signal reaches native auth; committed truth survives late invalidation",async()=>{const f=fixture();let seen:AbortSignal|undefined;const native=f.registry.configureIdleChild;f.registry.configureIdleChild=async r=>{seen=r.signal;const result=await native(r);f.controller.invalidate();return result;};const r=await f.controller.apply(f.binding,f.proposal(),f.runtime);expect(r.status).toBe("committed");expect(seen?.aborted).toBe(true);expect(f.controller.history(f.binding)).toHaveLength(1);expect((await f.controller.revert(f.binding,f.runtime)).status).toBe("rejected");});
});
