import { expect, test } from "bun:test";
import type { DecisionEntry } from "../../src/contracts";
import { actionGlyph, prepareStatus, pricingText } from "../../src/ui/status";
import { decisionEntryType, prepareDecision, projectEntry, registerRenderer } from "../../src/ui/entries";
import type { EntryRenderer } from "@earendil-works/pi-coding-agent";
import { emptyLedger, dayKey, monthKey, loadLedger } from "../../src/core/budget";
import { AccountingStore, ensureAccounting } from "../../src/state/accounting";
import { mkdtempSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { decide } from "../../src/core/router";
import { analysis, config } from "../support/fixtures";
const entry=():DecisionEntry=>({version:1,owner:"owner",child:"child",action:"proposed",reason:"routing",analysis:analysis({requestTruncation:{originalChars:9000,sentChars:8000}}),decision:decide(analysis(),config(),{models:[{provider:"openrouter",id:"openai/gpt-5.3-codex"}],spend:{today:1,month:2,pressure:.8}})});
for(const [action,glyph] of [["proposed","→"],["applied","→"],["held","="],["notified","•"],["skipped","×"],["preserved","="]] as const)
 test(`action glyph ${action}`,()=>{expect(actionGlyph(action)).toBe(glyph);expect(prepareDecision({...entry(),action},false)).toContain(glyph);});
test("compact and expanded show proposal separate from observed effective child settings",()=>{const e=entry();const compact=prepareDecision(e,false),expanded=prepareDecision(e,true,{model:"p/actual",thinking:"low"});expect(compact).toContain("proposed");expect(compact).not.toContain("effective: openrouter");expect(compact).toContain("effective: unobserved");expect(expanded).toContain("effective: p/actual (low)");for(const text of ["kind","complexity","conf","capability","reasoning","demand","budget pressure","truncated","reported spend"])expect(expanded).toContain(text);expect(compact).not.toContain("latency");});
test("expanded preserves raw numerical judgment and free/specialist/cache notes",()=>{const e=entry();e.analysis=analysis({complexity:1.7,budgetIntensity:1.55,deepReasoning:.82});if(!e.decision)throw Error("decision absent");e.decision.notes=["free pool → m","kind specialist","keeping warm cache"];const text=prepareDecision(e,true);for(const bit of ["1.70","1.55","82%","free pool","specialist","cache"])expect(text).toContain(bit);});
test("projection strips task/options/config/cost payloads and bounds strings",()=>{const e={...entry(),prompt:"SECRET",original:{apiKey:"SECRET"},reason:"r".repeat(5000)};const p=projectEntry(e);expect(JSON.stringify(p)).not.toContain("SECRET");expect(p.reason.length).toBeLessThanOrEqual(1024);});
test("why renderer no data fallback",()=>{expect(prepareDecision(undefined,true)).toContain("no decision data");});
test("malformed stored numeric judgment is unavailable, never fabricated as zero",()=>{const e=entry();if(!e.analysis)throw Error("analysis absent");e.analysis.complexity=NaN;expect(()=>projectEntry(e)).toThrow("invalid-decision-number");const text=prepareDecision(e,true);expect(text).toContain("decision data unavailable");expect(text).not.toContain("complexity 0.00");});
for(const shape of ["empty","legacy","mixed"])
 test(`pricing status stays incomplete: ${shape}`,()=>{const ledger=emptyLedger();if(shape!=="empty"){ledger.days[dayKey()]={total:shape==="mixed"?.2:0,byModel:{"unknown-child-model":shape==="mixed"?.2:0}};ledger.months[monthKey()]=ledger.days[dayKey()];}if(shape==="mixed")ensureAccounting(ledger);const text=pricingText(ledger);expect(text).toContain("pricing incomplete");expect(text).not.toContain("fully accounted");expect(text).not.toContain("free");expect(text).not.toContain("complete frontier");});
test("status separates reported dollars, unknown tokens, attribution and temporal gaps",()=>{const c=config();c.budget.dailyUsd=1;const ledger=emptyLedger();ledger.days[dayKey()]={total:.2,byModel:{"unknown-child-model":.2}};ledger.months[monthKey()]={total:.2,byModel:{"unknown-child-model":.2}};ledger.jev={requests:4,inputTokens:12,outputTokens:3};const envelope=ensureAccounting(ledger);envelope.evaluations.a={owner:"owner",toolCallId:"a",requests:1,status:"classified",usageStatus:"unavailable"};const text=prepareStatus({owner:"owner",generation:1,config:c},ledger,[],{discovery:"unknown",control:"unsupported",children:[]});for(const bit of ["Reported $0.200","pricing incomplete","attribution","unknown","12","3","unavailable","20%","advisory","concurrent","legacy-rounded-loss-unrecoverable"])expect(text).toContain(bit);expect(text).not.toContain("fake-key");});
test("unavailable ledger is never a reported zero",()=>{const text=prepareStatus({owner:"owner",generation:1,config:config()},undefined,[],{discovery:"unknown",control:"unsupported",children:[]});expect(text).toContain("Reported USD unavailable");expect(text).not.toContain("$0.0000");});
test("actual incomplete mixed aggregate exposes reason codes and late attribution",async()=>{const store=new AccountingStore(join(mkdtempSync(join(tmpdir(),"ui-money-")),"state.json"));const accountingId=await store.registerOrigin({backend:"@tintinweb/pi-subagents",rootOwnerId:"owner",spawnToolCallId:"spawn",childId:"c"},{owner:"owner",child:"c",generation:1});await store.observe({accountingId,authorizedOwner:"owner",child:"c",bindingGeneration:1,reportedCumulativeUsd:.2,provenance:"record-lifetime",aggregationScope:"top-level-including-descendants",pricing:{status:"incomplete",reasons:["unpriced-contribution","aggregate-loses-missing-cost"]},at:new Date().toISOString(),late:true});const text=prepareStatus({owner:"owner",generation:1,config:config()},loadLedger(store.file),[],{discovery:"unknown",control:"unsupported",children:[]});for(const token of ["Reported $0.200","unpriced-contribution","aggregate-loses-missing-cost","1 late observation","historical activity time unknown"])expect(text).toContain(token);expect(text).not.toContain("fully accounted");});
test("renderer absence does not load optional TUI",async()=>{let calls=0;expect(await registerRenderer({},async()=>{calls++;throw Error("missing");})).toBe(false);expect(calls).toBe(0);});
test("missing optional TUI gracefully declines registration",async()=>{let registered=false;expect(await registerRenderer({registerEntryRenderer:()=>{registered=true;}},async()=>{throw Error("not installed");})).toBe(false);expect(registered).toBe(false);});
test("actual renderer uses injected public primitives and correct namespace",async()=>{let render:EntryRenderer<DecisionEntry>|undefined;let name="";
 class Text {constructor(readonly text:string){}render(){return [this.text];}invalidate(){}}
 class Box {children:Text[]=[];addChild(child:Text){this.children.push(child);}render(){return this.children.flatMap(c=>c.render());}invalidate(){}}
 const result=await registerRenderer({registerEntryRenderer:<T>(n:string,r:EntryRenderer<T>)=>{name=n;render=r as EntryRenderer<DecisionEntry>;}},async()=>({Text,Box}));expect(result).toBe(true);expect(name).toBe(decisionEntryType);expect(name).not.toBe("jev-router-decision");if(!render)throw Error("renderer absent");const theme={fg:(_c:string,t:string)=>t,bg:(_c:string,t:string)=>t};const component=render({data:entry()} as never,{expanded:true},theme as never);expect(component?.render(200).join("\n")).toContain("complexity");
});
test("projected observed display pair reaches registered renderer without native data",async()=>{const display=projectEntry(entry(),{model:"observed/model",thinking:"off"});let render:EntryRenderer<DecisionEntry>|undefined;const ready=await registerRenderer({registerEntryRenderer:<T>(_n:string,r:EntryRenderer<T>)=>{render=r as EntryRenderer<DecisionEntry>;}});expect(ready).toBe(true);if(!render)throw Error("renderer absent");const theme={fg:(_c:string,t:string)=>t,bg:(_c:string,t:string)=>t};const rendered=render({data:display} as never,{expanded:true},theme as never);expect(rendered?.render(200).join("\n")).toContain("effective: observed/model (off)");});
test("throwing renderer registration is contained",async()=>{class Text{render(){return [];}invalidate(){}}class Box extends Text{addChild(){}}expect(await registerRenderer({registerEntryRenderer:()=>{throw Error("SECRET");}},async()=>({Text,Box}))).toBe(false);});
